### ISSUE TITLE
Getting Failed to start login Service!

### ISSUE THREAD

**Issue by mbzadegan** [BlackArch/blackarch#1633] opened 2017-05-09 14:51 UTC
Hi everybody,
I want to install BlackArch on my PC but I have poor internet connection speed and I must use ISO. Therefore I get this Error in the first boot!

[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.

Also I read issue #1618 but I can not installing BlackArch without ISO.
How can I do to resolve my problem?

**Comment by CoyoteScript** [comment] 2017-05-22 14:05
I've got the same issue. I installed BlackArch from ISO (2017.03.01 i686 iso) from USB. I followed the install guide (https://www.blackarch.org/blackarch-install.html) all the way through creating the partitions. When I reached the "fully Encrypt" via LUKS, I was only asked for confirmation twice. The last confirm requiring a "YES" entry never occurred. There was also no option for creating a user account via the Unix Password. 
Now, upon trying to boot the system, I get [Failed} in regards to Loading Kernel Modules and [Failed] Failed to start Login Services. At this last message, the system pretty much just stops dead. I'm also unable to boot any other Live ISO or install ISO of any sort. BlackArch just plows through and then hits it's dead end and sits there.

Comp Specs: Asus EeePC 900HD
https://www.cnet.com/products/asus-eee-pc-900hd-8-9-celeron-m-353-win-xp-home-1-gb-ram-120-gb-hdd-series/specs/

I've had issues with installing AbsoluteLinux on this little machine before, and I was wondering if being connected to the internet during install might have glitched something. In the AbsoLin install, User could not be created when the process was performed from LiveOS while online; I had to do it offline and then update afterwards. Could this be a similar issue?

**Comment by ikstream** [comment] 2017-05-22 15:31
This is an known bug.
Unfortunately there is no solution yet.
@CoyoteScript If you plan to update later anyways, you could try to install arch linux and add the black arch repository to it, when you are connected. You would have to look for an older iso of arch linux as they killed 32bit isos recently.

**Comment by ikstream** [comment] 2017-07-18 17:07
Have you tried the new ISO? The problem should be fixed.

**Comment by G0dlyLuck** [comment] 2017-07-28 14:44
For me the install finishes without problems BUT after reboot it hangs on [OK] reached target graphical interface when I am installing it in virtualbox. Im using an nvidia gtx 970M and got no clue how to fix it.

**Comment by ikstream** [comment] 2017-07-28 16:44
Did you use the new ISO?
If yes, could you please tell which one and if you installed from repo, or iso.
Have there been any failed entries before the system hangs?

**Comment by G0dlyLuck** [comment] 2017-07-28 19:17
I used the new Live ISO version 2017.06.04. I also installed from the Live ISO (option 2 from the top of my head). There have been some that failed although I cant exactly recall which ones failed (scrolls very fast). Ill have to check that again. Any thing I should look for/pay attention to?

**Comment by G0dlyLuck** [comment] 2017-07-31 16:38
I tried reinstalling the x86_64 bit iso multiple times but it doesnt seem to work. It keeps hanging at the ok reached target graphical interface line and the only error that i see is the failed to create volatile files and directories error. Im new arch and any way to retrieve error logs that i know off produces nothing. Is this a virtualbox only issue?

**Comment by ikstream** [comment] 2017-07-31 16:52
could you check if this 

"[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details." 

shows up for you as well?

**Comment by G0dlyLuck** [comment] 2017-07-31 17:57
No. The other one failing is failed to start load kernel modules.

**Comment by G0dlyLuck** [comment] 2017-07-31 20:07
Alright so I do not know why but I tried installing from repo and it works. So there must be an issue when using the LIVE ISO to install in virtualbox. The issue is that you cant log in and that the system hangs at reached target graphical interface.

**Comment by ikstream** [comment] 2017-08-01 16:20
This seems to be the same error as before. So the Login service seems not to be the problem of the initial error.

**Comment by ikstream** [comment] 2017-08-08 08:10
@G0dlyLuck If you are interested in running blackarch in a virtual enviroment you could check out https://github.com/ikstream/blackarch-virtualization 
This repo provides a vagrant base box and a docker image.

**Comment by G0dlyLuck** [comment] 2017-08-08 08:15
Cool thank you! But I already got it working in VBox. But ill check it out.

**Closed** 2017-08-13 17:02 UTC

**Comment by cha0tic75** [comment] 2017-12-05 07:11
Is there a solution to this issue?  I downloaded blackarchlinux-live-2017.11.24-x86_64.iso and followed the following tutorial: https://blackarch.org/blackarch-install.html
Everything seems to have installed, but when prompted for login:  It seems to be signing in, but returns to the signin screen.  I can hit ctrl Alt F2 to switch TTY2 and can sign in no problem.  Seems to be an issue with the x11 window login.  I installed into virtualbox, using the above ISO and selected install from repo. Any suggestions?  Thanks in advance.

**Comment by ikstream** [comment] 2017-12-05 09:51
@cha0tic75 have you tried [this](https://github.com/BlackArch/blackarch/issues/1820) already?

**Comment by cha0tic75** [comment] 2017-12-05 18:03
Thanks for your response.  I have tried switching Desktops, but like the post you refer to, there are only 2 options:  Default and Blackarch-dwm.  Both don't work.  As far as updating the installer, i haven't tried that.  I figured, since i downloaded the most recent ISO, it would have the proper installer.  Any suggestions on how to update the installer to V0.6.1?

**Comment by ikstream** [comment] 2017-12-06 22:01
Just try pacman -S blackarch-installer. This should update yout blackarch-installer to 0.6.1

**Comment by saajanbedi** [comment] 2017-12-09 12:54
pacman -Syy
pacman -S blackarch-installer
this will solve the problem.
