### ISSUE TITLE
The "nipe" tool does not work

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2011] opened 2018-09-02 13:37 UTC

**Comment by noptrix** [comment] 2018-09-02 19:17
what's the error?

**Comment by GasparVardanyan** [comment] 2018-09-05 16:37
Internet does not workin when nipe is enabled.

**Comment by Edu4rdSHL** [comment] 2018-09-11 15:46
I hope that when the next two commits are merged into nipe/master the problem is fixed.

Start.pm: https://github.com/GouveaHeitor/nipe/commit/5e5e8257b4fa423070741168949a0826de91c9e4

Stop.pm: https://github.com/GouveaHeitor/nipe/commit/2703585526258ab92a495e915c5f1719edd633bf

**Comment by GouveaHeitor** [comment] 2018-09-13 10:37
This has already been corrected, thanks to @Edu4rdSHL

**Closed** 2018-09-13 11:26 UTC
