### ISSUE TITLE
blackarch login error after augest update 2020

### ISSUE THREAD

**Issue by sahil-kazama** [BlackArch/blackarch#2836] opened 2020-08-25 04:39 UTC
sir i give you warning after update blackarch and i reboot into blackarch i have enter my valid user and passwd  and i unable to login in blackarch so said 
# please fix login problem i tried manually and i edit blacarch bootloader  < grub.cfg>  file to line      ro splash init=/bin/bash     and after i boot into recovery and i changed my login user and passwd of blackarch linux  and i after reboot my blackarch linux after i again enter my valid username and password but login does not accept 
# this is login error i try to fix this problem but i fail
# you all are great team for world 
# thanks for give this operating system for world and free 
# god bless you

**Comment by Edu4rdSHL** [comment] 2020-08-25 04:40
Duplicate of #2835

**Closed by Edu4rdSHL** 2020-08-25 04:40 UTC
