### ISSUE TITLE
VM Guest (BlackArch) in Virtualbox no start boot

### ISSUE THREAD

**Issue by firebitsbr** [BlackArch/blackarch#1040] opened 2016-04-02 21:55 UTC
Failed to start Load Kernel Modules
See "systemctl status systemd-mdules-load.service"

Similar:
https://bbs.archlinux.org/viewtopic.php?id=162417

**Comment by danillofa** [comment] 2016-04-19 01:45
firebitsbr, I have the same problem, however watched the following:

[ blackarch ~ ]# journalctl -f
-- Logs begin at Mon 2016-04-18 18:14:49 BRT. --
Apr 18 22:39:43 blackarch systemd[1]: lxdm.service: Failed with result 'exit-code'.
Apr 18 22:39:43 blackarch systemd[1]: lxdm.service: Service hold-off time over, scheduling restart.
Apr 18 22:39:43 blackarch systemd[1]: Stopped LXDE Display Manager.
Apr 18 22:39:43 blackarch systemd[1]: Started LXDE Display Manager.
Apr 18 22:39:48 blackarch systemd[1]: lxdm.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 22:39:48 blackarch systemd[1]: lxdm.service: Unit entered failed state.
Apr 18 22:39:48 blackarch systemd[1]: lxdm.service: Failed with result 'exit-code'.
Apr 18 22:39:48 blackarch systemd[1]: lxdm.service: Service hold-off time over, scheduling restart.
Apr 18 22:39:48 blackarch systemd[1]: Stopped LXDE Display Manager.
Apr 18 22:39:48 blackarch systemd[1]: Started LXDE Display Manager.
Apr 18 22:39:54 blackarch systemd[1]: lxdm.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 22:39:54 blackarch systemd[1]: lxdm.service: Unit entered failed state.
Apr 18 22:39:54 blackarch systemd[1]: lxdm.service: Failed with result 'exit-code'.
Apr 18 22:39:54 blackarch systemd[1]: lxdm.service: Service hold-off time over, scheduling restart.
Apr 18 22:39:54 blackarch systemd[1]: Stopped LXDE Display Manager.
Apr 18 22:39:54 blackarch systemd[1]: Started LXDE Display Manager.

The problem is when you start the graphical interface , I did a test with VMware Workstation and it usually works, more I would like to use VirtualBox.
Anyone know how to solve this problem ?

**Comment by noptrix** [comment] 2016-04-29 08:22
This has been fixed with the new installe released along the new ISOs.

**Closed by noptrix** 2016-04-29 08:22 UTC
