### ISSUE TITLE
[Tool Request] -  waymore

### ISSUE THREAD

**Issue by EsamLasheen** [BlackArch/blackarch#4033] opened 2023-12-16 14:40 UTC
- **Name**: waymore
- **Source URL**: https://github.com/xnl-h4ck3r/waymore
- **Description**: Find way more from the Wayback Machine!

**Comment by noraj** [comment] 2023-12-18 21:34
Duplicate of #3741

@EsamLasheen please search for existing issues before opening a new one.

**Closed by noraj** 2023-12-18 21:34 UTC
Labels: type::tool-request, lang::python
