### ISSUE TITLE
non-root user problem

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2039] opened 2018-09-11 10:45 UTC
I did fresh install of blackarch and when i create new user and run command with sudo ex :
sudo visudo
And i enter the password and come result
*user_name* is not in the sudoers file. This incident will be reported. 

Im using latest version of blackarch-installer 0.9

**Comment by FFY00** [comment] 2018-09-11 11:31
Well, you need to add your user to the sudoers file, `/etc/sudoers`. This needs to be done as root.

**Comment by Franchium** [comment] 2018-09-11 13:11
Yeah, i fix that problem by run visudo and add *user_name* ALL=(ALL) ALL
I just want report this so it'll fix on the next update

**Comment by FFY00** [comment] 2018-09-11 14:50
How did you install blackarch?

**Comment by ikstream** [comment] 2018-09-11 15:03
That's not really an issue, you just created a non root user during installation, that does not mean, it should be allowed in sudoers per default

**Comment by FFY00** [comment] 2018-09-11 15:05
@ikstream I actually didn't know our position here. Seems like the user created during install isn't added automatically to the sudoers file, right?

**Comment by ikstream** [comment] 2018-09-11 15:07
@FFY00 right! 
In my opinion this is intended behaviour.

**Comment by noptrix** [comment] 2018-09-11 15:50
yes: @Franchium @FFY00 @ikstream - this is intended. user should update sudoers on their own after installation. can we close this  issue here?

**Closed** 2018-09-11 19:47 UTC
