### ISSUE TITLE
wkhtmltopdf: outdated and seems no longer maintaining.

### ISSUE THREAD

**Issue by astro-angelfish** [BlackArch/blackarch#4165] opened 2024-06-22 10:08 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

wkhtmltopdf is no longer working. Invoking the command directly causes `wkhtmltopdf: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory` and I'm unable to build it by myself

Its repository is already archived and its website does not seem to be updated.

### Steps to reproduce

- Just execute `mkhtmltopdf`
- See the error

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

`wkhtmltopdf: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory`

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

It should at least print some help information

### Info for developers

**Device:** Hasee TX6-CU5DS with 16GB memory
**GNU/Linux distribution:** Arch Linux
**Tool version:** 0.12.6-2

### Link to debug log

`wkhtmltopdf: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory`

**Comment by D3vil0p3r** [comment] 2024-10-09 20:14
The issue is caused by `qt5-webkit` dependency because the BA version of this qt5 pkg has been compiled with previous libs. Once this PR has been merged and the mentioned tool rebuilt, it should work

https://github.com/BlackArch/blackarch/pull/4287

**Closed** 2024-10-10 21:38 UTC
Labels: type::bug
