### ISSUE TITLE
MongoDB package - Usage of mongodb-bin AUR package for BlackArch mongodb package

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3617] opened 2022-11-29 11:58 UTC
Type: Question

## Question

Hello, by doing some tests on the current PKGBUILD and related files of MongoDB BlackArch package, as described in the https://github.com/BlackArch/blackarch/issues/3605 issue that produced several errors during the compilation, I was thinking: is it possible to update the mongodb package in BlackArch as the mongodb-bin AUR package? I tested it and it is working correctly.
Check it by cloning the AUR package by:
```
git clone https://aur.archlinux.org/mongodb-bin.git
```
Thanks

**Comment by noraj** [comment] 2022-11-29 15:41
duplicate of #3605

**Closed by noraj** 2022-11-29 15:41 UTC
