### ISSUE TITLE
Casefile is not starting

### ISSUE THREAD

**Issue by myrage2000** [BlackArch/blackarch#1802] opened 2017-10-29 18:24 UTC
Casefile doesn't seem to work : it crashes when loading, with no console errors.

Here is my `java -version`:
`openjdk version "1.8.0_144"`
`OpenJDK Runtime Environment (build 1.8.0_144-b01)`
`OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)`

Can somebody confim this issue please ?

**Comment by noptrix** [comment] 2017-10-30 09:37
@myrage2000 yep, true. confirmed. but we need to upgrade casefile/maltego anyway. i will leave this ticket open until we upgraded successfully. thx for reporting this

**Comment by myrage2000** [comment] 2017-11-07 18:22
Thanks,
Since I need it for next week, I will try to update the PKGBUILD and pull request it.

**Comment by Edu4rdSHL** [comment] 2019-01-12 22:39
Closing because it's not reproducible now.

![virtualbox_blackarch-linux_12_01_2019_17_37_11](https://user-images.githubusercontent.com/32582878/51079198-f4d1c280-1690-11e9-98e4-3669ba0a84be.png)

**Closed by Edu4rdSHL** 2019-01-12 22:39 UTC
Labels: not-reproducible
