### ISSUE TITLE
Tor Proxy Chains Anonsurf VPN

### ISSUE THREAD

**Issue by CyberGhazi786** [BlackArch/blackarch#3589] opened 2022-11-22 11:43 UTC
- **Name**: Please add this easy tool to install Tor Proxychains AnonSurf TorBrowser -All in one
- **Source URL**: https://github.com/Und3rf10w/kali-anonsurf
- **Description**: AnonSurfing

**Comment by noraj** [comment] 2022-11-22 13:19
duplicate of #2922, please search before opening a new issue

**Closed by noraj** 2022-11-22 13:19 UTC
Labels: tool-request
