### ISSUE TITLE
empire: dependency issue

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3105] opened 2021-05-24 11:27 UTC
```
$ empire --rest
Traceback (most recent call last):
  File "/usr/share/empire/empire", line 29, in <module>
    from sqlalchemy import or_, and_, func
ModuleNotFoundError: No module named 'sqlalchemy'
```

After `sudo pacman -Syu python-sqlalchemy`:

```
$  empire --rest                     
Traceback (most recent call last):
  File "/usr/share/empire/empire", line 34, in <module>
    from lib.common import empire, helpers, users
  File "/usr/share/empire/lib/common/empire.py", line 42, in <module>
    from . import helpers
  File "/usr/share/empire/lib/common/helpers.py", line 73, in <module>
    from lib.database.base import Session
  File "/usr/share/empire/lib/database/base.py", line 8, in <module>
    from lib.database import models
  File "/usr/share/empire/lib/database/models.py", line 6, in <module>
    from sqlalchemy_utc import UtcDateTime
ModuleNotFoundError: No module named 'sqlalchemy_utc'
```
But some pypi package like `SQLAlchemy-Utc` and maybe others are not packaged in AL nor BA: https://github.com/BC-SECURITY/Empire/blob/master/setup/requirements.txt

So maybe it's time to move to a virtual env install, all those python dependencies are hard to maintain?

Also Empire project has no setup.py nor version handling in requirements.txt nor a lock file so managing their dependencies will always be a problem.

**Comment by Edu4rdSHL** [comment] 2021-05-27 07:09
Duplicate of #3086

**Closed by Edu4rdSHL** 2021-05-27 07:09 UTC
Labels: duplicate
