### ISSUE TITLE
[Package] sparta

### ISSUE THREAD

**Issue by gerardo-junior** [BlackArch/blackarch#1539] opened 2017-03-02 02:21 UTC
this error :
[-] Import failed. PyQt4 library not found. 
Try installing it with: apt-get install python-qt4

**Comment by aancw** [comment] 2017-03-16 04:53
Same with this https://github.com/BlackArch/blackarch/issues/1566

**Comment by noptrix** [comment] 2017-03-21 21:46
yeah, duplicate of #1566 - closing this ticket here

**Closed by noptrix** 2017-03-21 21:46 UTC
