### ISSUE TITLE
Stuck while installing

### ISSUE THREAD

**Issue by axay98** [BlackArch/blackarch#1818] opened 2017-11-22 14:30 UTC
I was installing blackarch using vmware work station but when i reached Dumping data from Live ISO ,
It was stuck at Installing /usr, please wait....
 Waited for more than 30min .. but it still there .

**Comment by PedroSFreitas** [comment] 2017-11-22 14:51
@axay98 

**Thanks for the feedback.**

Although I would suggest waiting more than 30 minutes, since the amount of data and the time needed to transmit from everything from the Live ISO to a virtual disk might be quite big and slow (we're talking about a couple of GB).
Unfortunately I don't have all the parameters to provide you an estimated time to complete that operation, neither does the installation script has (progress status). That said, the best thing is wait for a good amount of time.

If waiting isn't an option for you, I suggest you to choose the repository installation process and skip the installation of the tools; which you can do later after installation is done, choosing only the tools that you need/want.

**Comment by axay98** [comment] 2017-11-22 17:25
Thank you for the response .. i waited and installation was completed .. but now when i rebooted, im getting this error
"[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details."
Please help me in solving this .

**Comment by PedroSFreitas** [comment] 2018-03-06 13:43
Closing this as duplicate of https://github.com/BlackArch/blackarch/issues/1618.

**Closed by PedroSFreitas** 2018-03-06 13:43 UTC
Labels: type-scripts
