### ISSUE TITLE
llk issues

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2053] opened 2018-09-19 11:52 UTC
[root@blackarch ~]# llk
sh: /usr/etc/logkeys-start.sh: No such file or directory
[root@blackarch ~]#

**Comment by ikstream** [comment] 2018-09-19 11:58
Duplicate of #1999

**Closed by ikstream** 2018-09-19 11:58 UTC

**Comment by Franchium** [comment] 2018-09-19 13:41
I see thats too before, but there is no fix for that so i posted again
