### ISSUE TITLE
Sparta not working in archlinux

### ISSUE THREAD

**Issue by g0rwx** [BlackArch/blackarch#1566] opened 2017-03-14 14:43 UTC
$ sparta
[-] Import failed. PyQt4 library not found. 
Try installing it with: apt-get install python-qt4

**Comment by aancw** [comment] 2017-03-16 04:30
Hi, try to install this dependency:

python2-elixir
python2-lxml
python2-pyqt4

Reference: https://aur.archlinux.org/packages/sparta/

Need to update PKGBUILD.

**Comment by aancw** [comment] 2017-03-16 04:36
Hm... Nope. From official repo they say that you need to downgrade pyqt4 version:

https://github.com/SECFORCE/sparta/issues/59

or using this: 

https://stackoverflow.com/questions/37604532/python-2-7-11-importerror-cannot-import-name-qtwebkit-kali-linux-debian-8

**Comment by g0rwx** [comment] 2017-03-17 10:26
I tried everything.

But it failed.

**Comment by saltasatelites** [comment] 2017-03-18 15:41
Dirty solution in Archlinux.
Works for me.
Go to the sparta directory
Open sparta.py.  In line 22 delete QtwebKit at the end of the line. Only QtwebKit (don 't forget to delete the last ","
Save changes
Open /sparta/ui/view.py
Delete completly lines 16, 50, 51, 52, 116, 423, 424
Save changes

Thts all. Hope it helps you!!!!!

**Comment by NovaCygni** [comment] 2017-03-18 15:52
saltasatelites Solution confirmed working, if not a litte dirty as described :/ but, yeh, it works.

**Comment by g0rwx** [comment] 2017-03-18 16:49
my log..

Traceback (most recent call last):
  File "sparta.py", line 88, in <module>
    view = View(ui, MainWindow)						# View prep (gui)
  File "/usr/share/sparta/ui/view.py", line 39, in __init__
    self.startConnections()								# signal initialisations (signals/slots, actions, etc)
  File "/usr/share/sparta/ui/view.py", line 120, in startConnections
    self.connectHelp()		
  File "/usr/share/sparta/ui/view.py", line 429, in connectHelp
    self.ui.menuHelp.triggered.connect(self.helpWidget.show)
AttributeError: 'View' object has no attribute 'helpWidget'

**Comment by aancw** [comment] 2017-03-19 05:03
@saltasatelites This will be good if you provide diff file for comparing :+1:

**Comment by noptrix** [comment] 2017-03-19 09:57
hey guys. if the solution @saltasatelites mentioned works, i will provide a patched version and release it.

**Comment by NovaCygni** [comment] 2017-03-19 12:58
Working here with his solution.

**Comment by ChrisFernandez** [comment] 2017-04-03 20:47
I have a diff issue.. says cant find  
```
-] Import failed. Elixir library not found. 
Try installing it with: apt-get install python-elixir
```

and when I try to install python2.elixir it complaints about:
`python2-sqlalchemy<0.8`

**Comment by noptrix** [comment] 2017-04-08 10:50
should be fixed now.

**Closed by noptrix** 2017-04-08 10:50 UTC

**Comment by romoAlmudena** [comment] 2017-12-23 10:01
Working here with his solution.

**Comment by st3r30byt3** [comment] 2018-01-10 10:59
Hi all. Please check if the solution in the latest SPARTA commit works for you! Thanks!

**Comment by noptrix** [comment] 2018-01-10 12:10
@st3r30byt3 Sparta is working now. Thanks
