### ISSUE TITLE
Window Manager/Session Manager fonts/config issues

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2433] opened 2019-08-12 03:21 UTC
I tried to install blackarch with netinstall iso where i don't setup VirtualBox modules, VMware also blackarch linux tools and when it's finished i boot up and the screen look like this. I can't do anything, even the xterm don't work (can't opened) also there's no wallpaper on the background.

![IMG_20190812_022757](https://user-images.githubusercontent.com/41231953/62844304-9504ce00-bcea-11e9-9825-e64c1b700024.jpg)
![IMG_20190812_022830](https://user-images.githubusercontent.com/41231953/62844315-a352ea00-bcea-11e9-9013-76d21efae496.jpg)
![IMG_20190812_022843](https://user-images.githubusercontent.com/41231953/62844320-ae0d7f00-bcea-11e9-85ef-085aef1859d0.jpg)
![IMG_20190812_022637](https://user-images.githubusercontent.com/41231953/62844336-bfef2200-bcea-11e9-8e20-30120f5aa132.jpg)

**Comment by Edu4rdSHL** [comment] 2019-08-12 14:19
Hey @mrsmith0x00, @PedroSFreitas. Can you please check what's happening there? Looks like we need to include an additional package in the netinstall dependency tree to set the background.

Also seems that we're facing issues with fonts, a Spanish user has reported the same issue days ago.

**Comment by mrsmith0x00** [comment] 2019-08-13 09:41
@Franchium hello!
Could you try to re-install BA:
```
1. Do pacman -Syy blackarch-installer --noconfirm
2. Run blackarch-install
3. When you will be asked for a finding mirrors -> yes
```
Looking forward for your answer! :)

**Comment by Franchium** [comment] 2019-08-13 10:09
I can't connect to internet to update blackarch-installer before i run the blackarch-install scripts. But i try this scenario where i'm running first blackarch-install when it's reach connection step i cancel the installation then do an upgrade for blackarch-installer. After it upgraded i run the installer again, is it safe?

Blackarch-installer version 1.1.1 --> 1.1.4

**Comment by Franchium** [comment] 2019-08-13 10:50
I already re-install BA with latest version of blackarch-installer but still get the same result.

**Comment by Edu4rdSHL** [comment] 2019-08-13 23:11
The ISO has not problems, just configuration things made by the installer.

**Comment by Franchium** [comment] 2019-08-13 23:37
I recently try to install BA using the live iso rather than the netinstall iso. Then i choose install from repository using pacman options. And here what i got


![IMG_20190814_062615](https://user-images.githubusercontent.com/41231953/62984271-c6051000-be5c-11e9-9f8c-2422e88eccf7.jpg)
![IMG_20190814_062632](https://user-images.githubusercontent.com/41231953/62984280-cd2c1e00-be5c-11e9-9800-4ec151dab0ac.jpg)

**Comment by mrsmith0x00** [comment] 2019-08-15 11:57
@Franchium @Edu4rdSHL  I just installed BA from netinstall ISO in VM. I got the same.
Seems like that we have issue with some Arch Linux package...

**Comment by PedroSFreitas** [comment] 2019-08-15 12:14
Team,

**High chance this is related to the Terminus font.**

I did a small test and got similar issues with upstream (Arch Linux) `terminus-font` package. Using the TTF version of Terminus fixed the issue for me, however we need further tests.

For now I'm retrieving the `terminus-font-ttf` PKGBUILD file from AUR and creating a PR for BlackArch. But we then need to:

1. Potentially patch all configuration files using xos4 Terminus font; and \[1\]
2. Rebuild all packages and ISO to force an update to terminus-font-ttf.

Any ideas are welcome.

\[1\]:
![image](https://user-images.githubusercontent.com/12863160/63093810-f0c69580-bf3c-11e9-811a-6a10443fce35.png)
(in the image you can also see I'm now using `terminus-font-ttf` packages rather than the upstream `terminus-font`

**Comment by Edu4rdSHL** [comment] 2019-08-15 13:03
Hello, @PedroSFreitas thank you for the PR. Anyways, it should also be handled in the installer side, true @mrsmith0x00?

We can close it issue when the installer also be fixed.

**Comment by PedroSFreitas** [comment] 2019-08-15 13:11
I don't think the installer is the only place that need changes. As the screenshot above shows, there is the possibility we also need to change those configuration file due to the package/font naming.

But again, further tests are necessary.

**Comment by mrsmith0x00** [comment] 2019-08-15 14:13
@Edu4rdSHL yeah, also in installer.
@PedroSFreitas +1

**Comment by PedroSFreitas** [comment] 2019-08-15 20:55
I strongly suggest to keep this Issue open until further tests are performed to ensure the new TTF Terminus font will fix this. As I mentioned above, we may need to make changes in the configuration files that uses Terminus.

**Comment by Edu4rdSHL** [comment] 2019-08-15 21:00
Reopening because it was closed when the PR was merged.

**Comment by Franchium** [comment] 2019-08-16 02:36
Well, i did re-install BA and here's what i got this

![IMG_20190816_085455](https://user-images.githubusercontent.com/41231953/63139404-6ba8b280-c008-11e9-97ed-542eb8702759.jpg)
![IMG_20190816_085519](https://user-images.githubusercontent.com/41231953/63139415-77947480-c008-11e9-857e-1c2931306147.jpg)

**Comment by Edu4rdSHL** [comment] 2019-08-16 02:38
@Franchium the installer isn't fixed. We will update the issue status and labels when it's solved.

**Comment by PedroSFreitas** [comment] 2019-08-16 12:36
@Franchium could you please try to install `terminus-font-ttf`?: `pacman -Syy terminus-font-ttf`.
We believe it may be of one of the problems, among missing other fonts and font configuration.

**Comment by Franchium** [comment] 2019-08-16 13:10
@PedroSFreitas i did install it but nothing change.

**Comment by Edu4rdSHL** [comment] 2019-08-17 19:00
Hello, @Franchium. Can you test again? `pacman -Sy blackarch-installer` and see if the problem is fixed?

**Comment by Franchium** [comment] 2019-08-17 21:58
@Edu4rdSHL it's not fixed yet, the fonts problem in the login sessions still exist.

**Comment by noptrix** [comment] 2019-08-17 23:03
> @Edu4rdSHL it's not fixed yet, the fonts problem in the login sessions still exist.
@Franchium hi! please tell us more details rather than 'it is not fixed' ... which version of the installer did you use? was it '1.1.5'? also, we are still working on it. the fix is not officially finished. it's still in progress.

**Comment by Franchium** [comment] 2019-08-17 23:27
> @Franchium hi! please tell us more details rather than 'it is not fixed' ... which version of the installer did you use? was it '1.1.5'? did you use the netinstall iso or which mode did you choose to install? also, jfyi, we are still working on it. the fix is not officially finished. it's still in progress.

Sorry, i'm using installer v.1.1.5 and netinstall iso with installation mode install from repository using pacman.

**Comment by noptrix** [comment] 2019-08-18 00:17
> > @Franchium hi! please tell us more details rather than 'it is not fixed' ... which version of the installer did you use? was it '1.1.5'? did you use the netinstall iso or which mode did you choose to install? also, jfyi, we are still working on it. the fix is not officially finished. it's still in progress.
> 
> Sorry, i'm using installer v.1.1.5 and netinstall iso with installation mode install from repository using pacman.

I just reinstalled using netinstall ISO and upgraded the installer to 1.1.5 right after the ISO booted. I did the same steps like you and I can't reproduce it anymore. It seems to be fixed. Are you sure you upgraded the installer? Please check and let us know.

**Comment by Edu4rdSHL** [comment] 2019-08-18 13:45
@Franchium can you confirm if it's finally solved? We can't reproduce the issue anymore.

**Comment by noraj** [comment] 2019-09-03 18:29
@Edu4rdSHL #2457 seems highly related, see there is still a problem or if the new issue can be closed.

**Comment by Franchium** [comment] 2019-09-03 23:59
Actually this issue still exist in netinstall iso 2019.09.01

**Comment by Sirvod** [comment] 2019-09-04 15:05
Just yesterday i updated to 2019.09.01 version with pacman and login,openbox fonts are not readable new gnome desktop environment logs out instantly.

**Comment by Edu4rdSHL** [comment] 2019-09-04 23:23
I'm pretty sure that it's because [1](https://github.com/BlackArch/blackarch-installer/blob/ca7e36bf2e8068ac9eb4ef335a460d6bd01bc220/data/usr/share/lxdm/themes/BlackArch/gtkrc#L17-L35), [2](https://github.com/BlackArch/blackarch-installer/blob/ca7e36bf2e8068ac9eb4ef335a460d6bd01bc220/data/usr/share/blackarch/lxdm/themes/BlackArch/gtk.css#L10) and [3](https://github.com/BlackArch/blackarch-installer/blob/ca7e36bf2e8068ac9eb4ef335a460d6bd01bc220/data/usr/share/blackarch/lxdm/themes/BlackArch/gtkrc#L17-L35) still have the old fonts.

**Comment by Franchium** [comment] 2019-09-05 05:44
I'm currently not using Blackarch, maybe @Sirvod could try that.

**Comment by Sirvod** [comment] 2019-09-05 06:31
@Edu4rdSHL I've done everything you mentioned above and nothing has changed.

**Comment by noptrix** [comment] 2020-04-16 16:45
this should be already fixed

**Comment by 2WR3505** [comment] 2020-07-21 15:20
this isnt fixed, not even in the 2020 june 6 version

**Comment by 2WR3505** [comment] 2020-07-21 15:44
using the net install, my login is the same as the first image posted by the op

**Comment by Edu4rdSHL** [comment] 2020-07-21 22:01
@2WR3505 can you confirm if installing `terminus-font-ttf` fix the problem?

**Comment by 2WR3505** [comment] 2020-07-22 15:56
yep, it fixed the problem :)

**Closed** 2020-07-22 16:08 UTC
Labels: investigating

**Comment by Edu4rdSHL** [comment] 2020-07-22 16:09
@2WR3505 thank you for confirming. This should be fixed in the latest installer version being released now.
