### ISSUE TITLE
[Update request] paru

### ISSUE THREAD

**Issue by sTiKyt** [BlackArch/blackarch#3691] opened 2023-01-22 01:03 UTC
I'm getting ```warning: paru: local (1.11.1-1) is newer than blackarch (1.9.3-1)``` since forever, installed paru from AUR

You might want to update paru in repositories to latest version

**Comment by noraj** [comment] 2023-01-22 01:27
duplicate of https://github.com/BlackArch/blackarch/issues/3637

**Closed by noraj** 2023-01-22 01:27 UTC
