### ISSUE TITLE
SSl Connection timeout 

### ISSUE THREAD

**Issue by ioavv** [BlackArch/blackarch#3550] opened 2022-10-10 12:01 UTC
Hi, after i installed the BlackArch and updated i can't clone any GitHub repository and after waiting some minutes I'm getting this error 

fatal: unable to access 'https://github.com/torproject/tor/': SSL connection timeout

mirror list updated to fastest 

would you please guide me!

**Comment by noraj** [comment] 2022-10-10 16:42
> installed the BlackArch

How? ISO? Which? OVA?

For quicker support join the community on Matrix: https://www.blackarch.org/community.html

**Comment by noraj** [comment] 2022-10-10 20:44
And you tried ti install package over tor?

**Comment by arvand-io** [comment] 2022-10-11 21:28
> Could you also fill this template:
> 
> ```lisp
> 
> 
> - [ ] I have searched open and closed issues for duplicates
> - [ ] I am submitting a bug report for existing functionality that does not work as intended
> 
> ----------------------------------------
> 
> ### Bug description
> 
> Describe here the issue that you are experiencing.
> 
> ### Steps to reproduce
> 
> - using hyphens as bullet points
> - list the steps
> - that reproduce the bug
> 
> **Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
> 
> **Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
> 
> ### Screenshots
> 
> 
> 
> ### Info for developers
> 
> 
> **Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
> **GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
> **Tool version:** 0.0.0
> 
> ### Link to debug log
> 
> 
> ```
> 
> Your message doesn't hold enough information for us to understand what happens.

After i installed the BlackArch from slim ISO and updated the mirrorlist both for archlinux and blackarch to the highest speed i just updated the Repo via pacman -Syyuu, it upgrade well but sometimes i get error:

 failed retrieving file 'blackarch.db' from www.blackarch.org : Resolving timed out after 10000 milliseconds
error: failed to synchronize all databases (download library error)

on the other hand i can't clone any GitHub repository and after a while i get the error:

fatal: unable to access 'https://github.com/tensorflow/tensorflow/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443 

I updated the key ring via website FAQ 1st option

**Comment by arvand-io** [comment] 2022-10-11 21:34
the issue is the same when i use ' yay -S <package> ' and here the error: 
==> ERROR: Failure while downloading https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_106.0.5249.103-1_amd64.deb
    Aborting...

 here the details in pacman.conf   
 /etc/pacman.conf:

[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HoldPkg = pacman glibc
#XferCommand = /usr/bin/curl -C - -f %u > %o
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

#IgnorePkg   =
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Server = http://mirror.hostiran.ir/archlinux/$repo/os/$arch
#SigLevel = Optional TrustAll
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[blackarch]
Include = /etc/pacman.d/blackarch-mirrorlist

**Comment by noraj** [comment] 2022-10-12 08:54
It doesn't concern BA when you DL stuff from AL or AUR.

If you have issue maybe change you mirror in `/etc/pacman.d/blackarch-mirrorlist`, you could even use rankmirror https://wiki.archlinux.org/title/Mirrors#Ranking_an_existing_mirror_list

**Closed** 2023-07-09 20:16 UTC
Labels: offtopic::support
