### ISSUE TITLE
Still a problem with the strap.sh for existing arch installations

### ISSUE THREAD

**Issue by aremai** [BlackArch/blackarch#1122] opened 2016-08-20 17:23 UTC
Hi,

I recently commented on the closed issue #1047 (Cannot run strap.sh for install blackarch tool), but I suppose closed issues are not looked at. So please forgive me if I open another issue:

I still run into this problem...please see the below output:

```
+ MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.AkqE9bDI
+ trap 'rm -rf /tmp/blackarch_strap.AkqE9bDI' EXIT
+ cd /tmp/blackarch_strap.AkqE9bDI
+ fetch_keyring
+ curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.AkqE9bDI

```

Is there anything that I can take a look at, if it's an issue on my side?!

**Comment by icarter09** [comment] 2016-08-21 03:33
Odd. I just installed BlackArch on top of my pre-existing Arch install and had no problems.

**Comment by aremai** [comment] 2016-08-21 17:50
Hmm, is there anything that I could check or verify on my end?
What is usually the reason why this error would appear?

**Comment by heichblatt** [comment] 2016-08-21 18:12
Hi @aremai ,

please run these commands manually and post the output:

> curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
> gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
> gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig

Cheers.

**Comment by aremai** [comment] 2016-08-22 16:14
hi @heichblatt ,

```
gpg: key 63EC0ADBEA87E4E3: "Evan Teitelman <teitelmanevan@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

first I got this:```

gpg: assuming signed data in 'blackarch-keyring.pkg.tar.xz'
gpg: Signature made Sun Jan 19 17:36:55 2014 CET
gpg:                using RSA key 63EC0ADBEA87E4E3
gpg: Good signature from "Evan Teitelman <teitelmanevan@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4345 7715 66D7 6038 C7FE  B438 63EC 0ADB EA87 E4E3
```

then I signed the key myself...

```
gpg: assuming signed data in 'blackarch-keyring.pkg.tar.xz'
gpg: Signature made Sun Jan 19 17:36:55 2014 CET
gpg:                using RSA key 63EC0ADBEA87E4E3
gpg: Good signature from "Evan Teitelman <teitelmanevan@gmail.com>" [full]
Primary key fingerprint: 4345 7715 66D7 6038 C7FE  B438 63EC 0ADB EA87 E4E3

```

However, if I run "sudo ./strap.sh" I still get the 
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
error

**Comment by noptrix** [comment] 2016-08-22 21:03
@aremai do this: rm -rf /etc/pacman.d/gnupg. then remove all entries related to blackarch in your pacman.conf. then simply rerun strap.sh (don't forget to chmod +x). if that still fails, do this: pacman-key --populate ; pacman-key --update. let us know if it helped

**Comment by aremai** [comment] 2016-08-22 21:57
@noptrix 
I followed your advice and now I got the following, hmm..

sudo pacman-key --populate ; pacman-key --update
```
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
  -> Locally signing key 44D4A033AC140143927397D47EFD567D4C7EA887...
  -> Locally signing key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
==> Importing owner trust values...
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...
  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...
  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...
  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...
  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...
  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...
  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...
  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...
  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...
  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...
  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  67  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  67  signed:   7  trust: 67-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2016-10-19
==> ERROR: pacman-key needs to be run as root for this operation.
```
this is weird, because I executed it with sudo.

**Comment by heichblatt** [comment] 2016-08-22 22:05
> sudo pacman-key --populate ; pacman-key --update

You only executed the first command with sudo, the `pacman-key --update` got run as your non-sudo user.

**Comment by aremai** [comment] 2016-08-23 20:44
@heichblatt you're absolutely right, my eyes were tired :(

I now ran the command again, properly, and got the following:
```
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
  -> Locally signing key 44D4A033AC140143927397D47EFD567D4C7EA887...
  -> Locally signing key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
==> Importing owner trust values...
==> Disabling revoked keys in keyring...
  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...
  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...
  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...
  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...
  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...
  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...
  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...
  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...
  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...
  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...
  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...
==> Updating trust database...
gpg: next trustdb check due at 2016-10-19
==> Updating trust database...
gpg: next trustdb check due at 2016-10-19
```
after this i ran the strap.sh script again but stil got the error ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch

also I've done the exact same steps as described by @noptrix earlier but still ran into the same error :(

**Comment by noptrix** [comment] 2016-08-28 19:38
@aremai are you still getting the error?

**Comment by aremai** [comment] 2016-08-29 16:36
@noptrix unfortunately, i'm still getting the error :(

**Comment by SeniorJaGa** [comment] 2016-09-01 12:11
@aremai try now ;)

**Comment by aremai** [comment] 2016-09-01 18:51
as much as I love troubleshooting an issue, I think I might be giving up on this....whatever I try, I constantly run into the same issue over and over again. Clearly it must be an issue on my side, because it seems to work for you.

For what it's worth, I will post the output of what I just did.....

```
theresa@concave:~\ ~  $ sudo rm -rf /etc/pacman.d/gnupg/*
theresa@concave:~\ ~  $ sudo rm /etc/pacman.d/gnupg/.gpg-v21-migrated
```

```
theresa@concave:~\ ~  $ sudo pacman-key --init
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key A3A0FCB292CCC5A6 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/FBC1F78A3B5CC349715EEF78A3A0FCB292CCC5A6.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
```
```
theresa@concave:~\ ~  $ sudo pacman-key --populate ; sudo pacman-key --update
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 0E8B644079F599DFC1DDC3973348882F6AC6A4C2...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
  -> Locally signing key 91FFE0700E80619CEB73235CA88E23E377514E00...
  -> Locally signing key 44D4A033AC140143927397D47EFD567D4C7EA887...
  -> Locally signing key 27FFC4769E19F096D41D9265A04F9397CDFD6BB0...
  -> Locally signing key AB19265E5D7D20687D303246BA1DFB64FFF979E7...
==> Importing owner trust values...
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabling key F5A361A3A13554B85E57DDDAAF7EF7873CFD4BB6...
  -> Disabling key 7FA647CD89891DEDC060287BB9113D1ED21E1A55...
  -> Disabling key D4DE5ABDE2A7287644EAC7E36D1A9E70E19DAA50...
  -> Disabling key BC1FBE4D2826A0B51E47ED62E2539214C6C11350...
  -> Disabling key 9515D8A8EAB88E49BB65EDBCE6B456CAF15447D5...
  -> Disabling key 4A8B17E20B88ACA61860009B5CED81B7C2E5C0D2...
  -> Disabling key 63F395DE2D6398BBE458F281F2DBB4931985A992...
  -> Disabling key 0B20CA1931F5DA3A70D0F8D2EA6836E1AB441196...
  -> Disabling key 8F76BEEA0289F9E1D3E229C05F946DED983D4366...
  -> Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
  -> Disabling key 81D7F8241DB38BC759C80FCE3A726C6170E80477...
  -> Disabling key E7210A59715F6940CF9A4E36A001876699AD6E84...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  67  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  67  signed:   7  trust: 67-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2016-10-19
==> Updating trust database...
gpg: next trustdb check due at 2016-10-19
```
```
theresa@concave:~\ ~  $ sudo ./strap.sh 
[+] installing blackarch keyring...
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
```

Thanks to all who were helping on this, but I really feel like I'm wasting your time, because nothing works....

**Comment by SeniorJaGa** [comment] 2016-09-02 06:10
@aremai Run strap.sh with 'sudo sh -x ./strap.sh' and paste the whole output here again please.

**Comment by aremai** [comment] 2016-09-02 16:50
`+ MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.WmEO8RjU
+ trap 'rm -rf /tmp/blackarch_strap.WmEO8RjU' EXIT
+ cd /tmp/blackarch_strap.WmEO8RjU
+ fetch_keyring
+ curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.WmEO8RjU
`

**Comment by heichblatt** [comment] 2016-09-02 17:51
Hi @aremai,

in case you're not tired yet, would you mind running `sudo sh -xe ./strap.sh` and posting the output? The added `e` will make the script stop on the first command that does not return 0. I'm not completely sure the `gpg --keyserver-options no-auto-key-retrieve ...` is the offender here, it might be the command before that, i.e. not being able to pull the correct key.

Cheers.

**Comment by aremai** [comment] 2016-09-02 18:17
Hi @heichblatt,

i'm not tired yet... I just thought I'd save you the troubles that you'd have to bear with me ;)
here we go, output from the -xe ... 

```
+ MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.DxjmRjtH
+ trap 'rm -rf /tmp/blackarch_strap.DxjmRjtH' EXIT
+ cd /tmp/blackarch_strap.DxjmRjtH
+ fetch_keyring
+ curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.DxjmRjtH

```

DANKE ;)

**Comment by heichblatt** [comment] 2016-09-02 19:28
As much as I try, I cannot reproduce this reliably, I'm sorry.

If you want to and absolutely understand the implications, you could comment out the `verify_keyring` function. I realize, however, that this would not actually be a proper solution. It's a workaround for a situation where I'd guess something else, local to your machine, is in play which keep this from working.

`strap.sh` works on a vanilla Arch install:

```
$ vagrant init --minimal terrywang/archlinux
$ vagrant up
$ vagrant ssh
(VM) $ sudo -i
(VM) $ curl https://blackarch.org/strap.sh | sh -xe -   # I know, I know.
(VM) $ echo $?
(VM) 0
```

**Comment by heichblatt** [comment] 2016-09-03 21:34
Hi @aremai,

as I said, since this is not reproducible outside of your system, I close this issue. If you have any new information or additional questions, don't hesitate to comment.

Viele Grüße. :wave:

**Closed by heichblatt** 2016-09-03 21:34 UTC

**Comment by jlaney21** [comment] 2016-12-26 04:06
I have found a work around for the issue in this thread if anyone is interested.

**Comment by scrigoose** [comment] 2017-01-19 23:46
[This](https://github.com/BlackArch/blackarch/issues/1047) thread I suppose.

**Comment by Zhidomasson** [comment] 2017-03-13 03:08
I still haven't found it. Always are some  mistakes.  Which is the solution?

**Comment by BruceLEO1969** [comment] 2017-04-23 06:53
Just delete the line:
> --keyserver http://pgp.mit.edu \

everything goes OK.

**Comment by yanganto** [comment] 2017-11-23 12:56
I delete the line
> --keyserver pgp.mit.edu

and still got the error
> [+] installing blackarch keyring...
> [-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch

Do the script still work?

**Comment by PedroSFreitas** [comment] 2017-11-23 13:19
@yanganto 

You **do not** need to delete that line, in fact, deleting it will mess up with the script; for sure.
The "invalid keyring..." error message is the first message the script will throw if one of the following errors occur:

1. You don't have an internet connection (as you can imagine, a rare issue and can be verify quickly);
2. You may have a DNS problem, that can't resolve pgp.mit.edu accordingly;
3. You may have a network issue, different from the above one, which is hard for us to help you since it can be a myriad of things (once someone figured out it was a dns cache thing;
4. You may have a clock/time issue, make sure to check that;
5. You may have something blocking your communication with mit.edu server, as for example: firewall. Make sure to check that;

It is usually a good idea to avoid commenting on a closed issue. You can always open a new one, if there isn't already one **opened** and possibly reference any closed issue that is similar to yours.

Try to test everything that I said above, use the Archlinux Wiki pages to assist you; if needed.

### Another thing that you could try is replacing the `pgp.mit.edu` for its IP address `18.9.60.141`. The following command, ran on the same directory of `strap.sh` will do the same:
```
$ sed -i "s|pgp.mit.edu|18.9.60.141|g" strap.sh
```
Make sure to test it.

### Here are some logs from today showing that everything is working just fine:
```
/home/psf/tmp [psf@cerb-pi] [11:13]
> ll
total 12K
-rwxr-xr-x 1 psf psf 3.9K Nov 23 11:12 strap-new.sh
-rwxr-xr-x 1 psf psf 3.9K Oct 18 19:31 strap.sh

/home/psf/tmp [psf@cerb-pi] [11:13]
> sha1sum * 
a70578c7ab5ff86b0a5d77237cb8ca85007dc76f  strap-new.sh
6f152b79419491db92c1fdde3fad2d445f09aae3  strap.sh

/home/psf/tmp [psf@cerb-pi] [11:13]
> diff strap-new.sh strap.sh 
54c54
<         --keyserver 18.9.60.141 \
---
>         --keyserver pgp.mit.edu \

/home/psf/tmp [psf@cerb-pi] [11:13]
> 
```

### **The vanilla `strap.sh` output from a Pi 3 running Archlinux ARM**:
```
/home/psf/tmp [psf@cerb-pi] [11:13]           
> sudo ./strap.sh                                                   
[sudo] password for root:                                           
[+] installing blackarch keyring...                                 
loading packages...                                                 
warning: blackarch-keyring-20140118-3 is up to date -- reinstalling
resolving dependencies...     
looking for conflicting packages...

Packages (1) blackarch-keyring-20140118-3
                              
Total Installed Size:  0.04 MiB      
Net Upgrade Size:      0.00 MiB                                                                                                                      
                                                                                                                                                     
:: Proceed with installation? [Y/n]                                                                                                                  
(1/1) checking keys in keyring                                                            [####################################################] 100%
(1/1) checking package integrity                                                          [####################################################] 100%
(1/1) loading package files                                                               [####################################################] 100%
(1/1) checking for file conflicts                                                         [####################################################] 100%
:: Processing package changes...
(1/1) reinstalling blackarch-keyring                                                      [####################################################] 100%
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key A0917C4147A37007CB54C1CFD295AA940EFDDF62...
  -> Locally signing key 4345771566D76038C7FEB43863EC0ADBEA87E4E3...
  -> Locally signing key CBA3C7D4798912702DCF568E67D8BDF42AD93F4E...
  -> Locally signing key 8F9A9793CB8591147C2EC70566E0CDBD1E01F333...
==> Importing owner trust values...
==> Updating trust database...
gpg: no need for a trustdb check
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key A0917C4147A37007CB54C1CFD295AA940EFDDF62...
  -> Locally signing key 4345771566D76038C7FEB43863EC0ADBEA87E4E3...
  -> Locally signing key CBA3C7D4798912702DCF568E67D8BDF42AD93F4E...
  -> Locally signing key 8F9A9793CB8591147C2EC70566E0CDBD1E01F333...
==> Importing owner trust values...
==> Updating trust database...
gpg: no need for a trustdb check

[+] keyring installed successfully
[+] updating package databases
:: Synchronizing package databases...
 core                                                            211.0 KiB   209K/s 00:01 [####################################################] 100$
 extra                                                             2.3 MiB   608K/s 00:04 [####################################################] 100$
 community                                                         4.5 MiB  4.06M/s 00:01 [####################################################] 100$
 alarm                                                           116.9 KiB  3.80M/s 00:00 [####################################################] 100$
 aur                                                               8.4 KiB   843K/s 00:00 [####################################################] 100$
 blackarch                                                      1975.8 KiB  1620K/s 00:01 [####################################################] 100$
[+] BlackArch Linux is ready!
```

You shall get the same output using the IP address of pgp.mit.edu server.

**Comment by yanganto** [comment] 2017-12-04 14:49
@PedroSFreitas Thanks for your info. I tried this solution, but still the same result. Besides, I try with https://pgp.mit.edu or http://pgp.mit.edu. 

> 
> ┌─[yanganto@yanganto-TP] - [/tmp] - [Mon Dec 04, 22:43]
> └─[$] <> sed -i "s|pgp.mit.edu|18.9.60.141|g" strap.sh
> ┌─[yanganto@yanganto-TP] - [/tmp] - [Mon Dec 04, 22:44]
> └─[$] <> sha1sum strap.sh
> a70578c7ab5ff86b0a5d77237cb8ca85007dc76f  strap.sh
> ┌─[yanganto@yanganto-TP] - [/tmp] - [Mon Dec 04, 22:44]
> └─[$] <> sudo ./strap.sh
> [sudo] password for yanganto:
> [+] installing blackarch keyring...
> [-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
> ┌─[yanganto@yanganto-TP] - [/tmp] - [Mon Dec 04, 22:45]
> └─[$] <>
> 
>
