### ISSUE TITLE
Nvidia / Xorg issue after install

### ISSUE THREAD

**Issue by proxymus89** [BlackArch/blackarch#1153] opened 2016-08-27 22:15 UTC
Hi 
i'm a new user of "Arch world" (I've allways used Kali linux), but my friends hint me to try Blackarch, I've an issue with graphic driver and Xorg after installation,I'm trying from 3 days to solve but nothing work, this is my history:
Assumption: I have a Nvidia GTX 970 and a Dell monitor 2K
- Start Blackarch from USB Pen, but display go to "no signal". Fast search in internet and i solve problem adding parameter "nouveau.modeset=0"
- GUI start regulary at resolution of 1024x768
- Start installation and all complete fine
- Restart
- From GRUB, i must add parameter "nomodeset", if I miss it i have again "no signal" message from display
- GUI start at very low resolution (640x480)
- Install Nvidia driver 
pacman -S nvidia
, all ok
- Restart and all is ok, but resolution is still 640x480
- Launch command 
nvidia-xconfig
which generate xorg.conf in /etc/X11/ 
- Restart
- After boot, before start GUI, all freeze at

[OK] Reached target Graphical Interface

in this terminal/window i can't do anything, is all freeze, so I press alt+ctrl+f2 to pass in another terminal, it works but with 2 minor problem:
1) every 4-5 seconds it take me back to 1st screen, so i must re-press alt+ctrl+f2 again
2) keyboard layout is different from usually
with difficult i can login in second screen/terminal, and from here, if I launch the command
rm /etc/X11/xorg.conf
automatically take me back on 1st screen and start GUI 
So the problem should be in the Xorg.conf, for some reason nvidia-xconfig command doesn't work properly

in /var/log/Xorg.0.log

[Log](http://pastebin.com/iZeTTWsE)

this is my xorg.conf

[Xorg.conf](http://pastebin.com/DQYs2SQx)

Can you help me please?I've tried all, I've reinstalled severy time the OS,  install/uninstall nouveau, vesa,intel, nvidia, nvidia-beta, i've also downloaded driver from nvidia official site and installed them manually, but the error is allways the same, it freeze at  
[OK] Reached target Graphical Interface
. I think the driver nvidia is ok, the problem is in configuration, or something i miss
ps. sorry for my bad english, I hope you understand all

**Comment by heichblatt** [comment] 2016-08-29 13:22
Hello @proxymus89,

I think you would get the best response if you asked at the [Arch Linux Forum](https://bbs.archlinux.org/), since none of the packages involved are modified in any way by BlackArch and it is highly unlikely that the problem is BlackArch-specific.

Let me know if it's OK to close this issue.

**Comment by proxymus89** [comment] 2016-08-29 19:08
Hi @heichblatt ,

It's very funny because before write here I've wrote on Arch Linux Forum, but they close my Thread because forum's rules not permit question about "other linux distro or arch derivated distro(like BlackArch)" and they hint me to ask on a "BlackArch forum"(which doesn't exist), so i ask here :D


However fortunately I solved by installing "nvidia-dkms" and "linux-headers". I don't know why, but after this works perfectly! :) thanks anyway

**Comment by heichblatt** [comment] 2016-08-30 06:30
Glad you found a solution.

**Closed by heichblatt** 2016-08-30 06:30 UTC
