### ISSUE TITLE
install ivre GUI

### ISSUE THREAD

**Issue by poyan94** [BlackArch/blackarch#2893] opened 2020-10-28 07:53 UTC
Hello My friends, I have installed blackarch, and I want to access IVRE via web access (i mean GUI),
first of all, I set an IP for my blackarch, and now I want to access IVRE through my network with GUI
What should I do exactly?

**Comment by noraj** [comment] 2020-10-28 19:00
duplicate of #2892

**Closed by noraj** 2020-10-28 19:00 UTC
