### ISSUE TITLE
Another Blackarch Signature Error - Cant Update/install any tools Due to Invalid Signature. 

### ISSUE THREAD

**Issue by spoooky762** [BlackArch/blackarch#4020] opened 2023-12-04 04:58 UTC
Type: Question

Hey guys so Heres the issue As mentioned in the title I cant Update or Install any Packages from the blackarch Repo Due to this Error ~> "error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid"
i might have missed somthing but have tried the usual fixes like manually signing the key, removing the repo & keyring then reinstalling it even just deleting The sig causing the Error hasnt fixed it, ive set pacmans SigTrustLevel To TrustAll as unsafe as that is but still nope Doesnt wanna play ball.
I have Tried all the fixes in the official FAQ on Blackarch's Domain and Done my due diligence in Official Arch Manual Troubleshooting so im out of ideas. Any help or advice is appreiciated, Cheers peeps :)

**Comment by anunna** [comment] 2023-12-07 11:50
Duplicate of #4018

I posted a temp solution.

**Closed as completed by anunna** 2023-12-07 11:50 UTC
Labels: offtopic::support
