### ISSUE TITLE
Dradis-CE installation/upgrade fails

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2897] opened 2020-10-30 02:31 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Dradis-CE fails post installation step

### Steps to reproduce

- `pacman -S dradis-ce`
- Watch it fail

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Post-installation errors out. Traceback: 

```
(1/1) reinstalling dradis-ce                                    [##################################] 100%
warning: directory permissions differ on /usr/share/dradis-ce/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/branches/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/hooks/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/info/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/logs/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/logs/refs/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/logs/refs/heads/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/logs/refs/remotes/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/logs/refs/remotes/origin/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/objects/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/objects/info/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/objects/pack/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/refs/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/refs/heads/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/refs/remotes/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/refs/remotes/origin/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/.git/refs/tags/
filesystem: 775  package: 755

-- SNIP--

warning: directory permissions differ on /usr/share/dradis-ce/vendor/assets/fonts/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/vendor/assets/images/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/vendor/assets/javascripts/
filesystem: 775  package: 755
warning: directory permissions differ on /usr/share/dradis-ce/vendor/assets/stylesheets/
filesystem: 775  package: 755
== Installing dependencies ==
The git source https://github.com/dradis/dradis-calculator_cvss.git is not yet checked out. Please run
`bundle install` before trying to start your application
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root
will break this application for all non-root users on this machine.
Fetching https://github.com/dradis/dradis-calculator_cvss.git
Fetching https://github.com/dradis/dradis-calculator_dread.git
Fetching https://github.com/dradis/dradis-csv.git
Fetching https://github.com/dradis/dradis-html_export.git
Fetching https://github.com/dradis/dradis-acunetix.git
Fetching https://github.com/dradis/dradis-brakeman.git
Fetching https://github.com/dradis/dradis-burp.git
Fetching https://github.com/dradis/dradis-metasploit.git
Fetching https://github.com/dradis/dradis-nessus.git
Fetching https://github.com/dradis/dradis-nexpose.git
Fetching https://github.com/dradis/dradis-netsparker.git
Fetching https://github.com/dradis/dradis-nikto.git
Fetching https://github.com/dradis/dradis-nmap.git
Fetching https://github.com/dradis/dradis-ntospider.git
Fetching https://github.com/dradis/dradis-openvas.git
Fetching https://github.com/dradis/dradis-qualys.git
Fetching https://github.com/dradis/dradis-saint.git
Fetching https://github.com/dradis/dradis-zap.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies........
Using rake 13.0.1
Using RedCloth 4.3.2
Using concurrent-ruby 1.1.7
Using i18n 1.8.5
Using minitest 5.14.2
Using thread_safe 0.3.6
Using tzinfo 1.2.7
Using activesupport 5.2.4.4
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.8
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.7.0
Using rails-html-sanitizer 1.3.0
Using actionview 5.2.4.4
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 5.2.4.4
Using nio4r 2.5.3
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Using actioncable 5.2.4.4
Using globalid 0.4.2
Using activejob 5.2.4.4
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailer 5.2.4.4
Using activemodel 5.2.4.4
Using arel 9.0.0
Using activerecord 5.2.4.4
Using mimemagic 0.3.5
Using marcel 0.3.3
Using activestorage 5.2.4.4
Using acts_as_tree 2.7.1
Using addressable 2.4.0
Using ast 2.4.0
Using execjs 2.7.0
Using autoprefixer-rails 9.7.4
Using bcrypt 3.1.12
Using bindex 0.8.1
Using blankslate 3.1.3
Using msgpack 1.3.3
Using bootsnap 1.4.5
Using popper_js 1.16.0
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.4.4
Using ffi 1.13.1
Using sassc 2.4.0
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using bootstrap 4.3.1
Using brakeman 4.7.2
Using uniform_notifier 1.13.0
Using bullet 6.1.0
Using bundler 2.1.4
Using bundler-audit 0.6.1
Using byebug 11.1.1
Using cancancan 1.17.0
Using regexp_parser 1.6.0
Using xpath 3.2.0
Using capybara 3.31.0
Using childprocess 3.0.0
Using chronic 0.10.2
Using coderay 1.1.2
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using coffee-rails 4.2.2
Using combustion 0.6.0
Using database_cleaner 1.8.2
Using descendants_tracker 0.0.4
Using diff-lcs 1.3
Using differ 0.1.2
Using dradis-plugins 3.18.0
Using dradis-acunetix 3.19.0 from https://github.com/dradis/dradis-acunetix.git (at master@ecb15a7)
Using jbuilder 2.10.0
Using dradis-api 0.0.1 from source at `engines/dradis-api`
Using dradis-brakeman 3.19.0 from https://github.com/dradis/dradis-brakeman.git (at master@713cece)
Using dradis-burp 3.20.0 from https://github.com/dradis/dradis-burp.git (at master@5701b7a)
Using dradis-calculator_cvss 3.19.0 from https://github.com/dradis/dradis-calculator_cvss.git (at master@3accfa5)
Using dradis-calculator_dread 3.20.0 from https://github.com/dradis/dradis-calculator_dread.git (at master@3534ca0)
Using dradis-csv 3.19.0 from https://github.com/dradis/dradis-csv.git (at master@b515830)
Using rails 5.2.4.4
Using rails_autolink 1.1.6
Using dradis-html_export 3.20.0 from https://github.com/dradis/dradis-html_export.git (at master@e09d0ac)
Using dradis-metasploit 3.19.0 from https://github.com/dradis/dradis-metasploit.git (at master@df06a57)
Using dradis-nessus 3.19.0 from https://github.com/dradis/dradis-nessus.git (at master@7de72da)
Using dradis-netsparker 3.19.0 from https://github.com/dradis/dradis-netsparker.git (at master@6f0678e)
Using dradis-nexpose 3.19.0 from https://github.com/dradis/dradis-nexpose.git (at master@4c123a9)
Using dradis-nikto 3.19.0 from https://github.com/dradis/dradis-nikto.git (at master@5bea12f)
Using rprogram 0.3.2
Using ruby-nmap 0.10.0
Using dradis-nmap 3.19.0 from https://github.com/dradis/dradis-nmap.git (at master@32724f2)
Using dradis-ntospider 3.19.0 from https://github.com/dradis/dradis-ntospider.git (at master@6c949fd)
Using dradis-openvas 3.19.0 from https://github.com/dradis/dradis-openvas.git (at master@c0aae17)
Using rubyzip 2.2.0
Using dradis-projects 3.18.0
Using dradis-qualys 3.19.0 from https://github.com/dradis/dradis-qualys.git (at master@1f30d42)
Using rspec-support 3.9.2
Using rspec-core 3.9.1
Using rspec-expectations 3.9.0
Using rspec-mocks 3.9.1
Using rspec-rails 3.9.0
Using dradis-saint 3.19.0 from https://github.com/dradis/dradis-saint.git (at master@9395276)
Using dradis-zap 3.19.0 from https://github.com/dradis/dradis-zap.git (at master@8efbcda)
Using factory_bot 5.1.1
Using factory_bot_rails 5.1.1
Using multipart-post 2.1.1
Using faraday 0.9.2
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.1
Using sass-listen 4.0.0
Using sass 3.7.4
Using font-awesome-sass 4.7.0
Using foreman 0.87.0
Using formatador 0.2.5
Using rchardet 1.8.0
Using git 1.6.0
Using hashie 4.1.0
Using mime-types 2.99.3
Using jwt 2.2.1
Using multi_json 1.14.1
Using multi_xml 0.6.0
Using oauth2 1.4.3
Using github_api 0.16.0
Using ruby_dep 1.5.0
Using listen 3.1.5
Using lumberjack 1.2.4
Using nenv 0.3.0
Using shellany 0.0.1
Using notiffany 0.1.3
Using pry 0.12.2
Using guard 2.16.1
Using guard-compat 1.2.1
Using rspec 3.9.0
Using guard-rspec 4.7.3
Using highline 2.0.3
Using html-pipeline 2.12.3
Using image_size 1.3.1
Using jaro_winkler 1.5.4
Using psych 3.1.0
Using rdoc 6.2.1
Using semver2 3.4.2
Using jeweler 2.3.9
Using jquery-fileupload-rails 0.3.5
Using jquery-hotkeys-rails 0.7.9.1
Using jquery-rails 4.3.5
Using jquery-ui-rails 6.0.1
Using json 2.3.0
Using kaminari-core 1.2.1
Using kaminari-actionview 1.2.1
Using kaminari-activerecord 1.2.1
Using kaminari 1.2.1
Using kgio 2.11.3
Using launchy 2.4.3
Using letter_opener 1.7.0
Using libv8 7.3.492.27.1 (x86_64-linux)
Using local_time 2.1.0
Using systemu 2.6.5
Using macaddr 1.7.2
Using mini_racer 0.2.9
Using mocha 1.11.2
Using mono_logger 1.1.0
Using ruby2_keywords 0.0.2
Using mustermann 1.1.1
Using nokogumbo 2.0.2
Using request_store 1.5.0
Using paper_trail 10.3.1
Using parallel 1.19.1
Using parser 2.7.0.2
Using parslet 1.6.2
Using puma 4.3.5
Using rack-protection 2.0.2
Using rainbow 3.0.0
Using raindrops 0.19.1
Using record_tag_helper 1.0.1
Using redis 4.1.3
Using redis-namespace 1.7.0
Using redisk 0.2.2
Using rerun 0.13.0
Using sinatra 2.0.2
Using vegas 0.1.11
Using resque 2.0.0
Using shoulda-context 1.2.2
Using shoulda-matchers 3.1.3
Using shoulda 3.6.0
Using uuid 2.3.9
Using resque-status 0.3.0
Using rinku 2.0.6
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.6.1
Using rubocop 0.79.0
Using sanitize 5.2.1
Using sass-rails 6.0.0
Using selenium-webdriver 3.142.7
Using simple_form 5.0.2
Using spring 2.1.0
Using spring-watcher-listen 2.0.1
Using sqlite3 1.4.2
Using timecop 0.9.1
Using turbolinks-source 5.2.0
Using turbolinks 5.2.1
Using uglifier 4.2.0
Using unicorn 5.4.1
Using warden 1.2.8
Using web-console 3.7.0
Using webdrivers 4.2.0
Using whenever 1.0.0
Bundle complete! 85 Gemfile dependencies, 212 gems now installed.
Bundled gems are installed into `./vendor/bundle`

== Updating database ==
rails aborted!
LoadError: cannot load such file -- /usr/lib/ruby/gems/2.7.0/gems/json-2.3.0/lib/json.rb
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/core_ext/object/json.rb:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/core_ext/object.rb:13:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/configuration.rb:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie/configuration.rb:3:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:223:in `config'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:127:in `config'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/i18n_railtie.rb:11:in `<class:Railtie>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/i18n_railtie.rb:10:in `<module:I18n>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/i18n_railtie.rb:9:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/railtie.rb:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails.rb:17:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activemodel-5.2.4.4/lib/active_model/railtie.rb:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/config/application.rb:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
/usr/share/dradis-ce/Rakefile:4:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/dradis-ce/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:migrate"] failed ==
error: command failed to execute correctly
```

**Expected result:**

Post-installation should finish without any errors

### Info for developers

**Tool version:**  `dradis-ce-3641.21d1090a-1`

**Comment by Edu4rdSHL** [comment] 2020-12-20 01:56
This problem has been fixed and the issue isn't reproducible anymore, closing.

Image from a containerized installation, `dradis-ce 3652.06a8dc99-1`:

![image](https://user-images.githubusercontent.com/32582878/102703414-74347d00-423c-11eb-8fab-f7b350551abb.png)

**Closed by Edu4rdSHL** 2020-12-20 01:56 UTC
Labels: bug, lang::ruby
