### ISSUE TITLE
pth-toolkit missing 32-bit Libraries: libcrypt.so.1 & libreadline.so.6

### ISSUE THREAD

**Issue by null-hyp0thesis** [BlackArch/blackarch#4161] opened 2024-06-18 14:22 UTC
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Hi
There are missing dependencies for the pth-toolkit package,
Two 32-bit libraries are missing from `/usr/lib` in a standard installation.

### Steps to reproduce

- Install pth-toolkit from Pacman
- Attempt to run a tool, i.e. `pth-net` 
- Issue 1: Verify the error appears:
`bin/net: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

- Issue 2: Fixing the first issue, a second error is encountered on execution of pth-net:
`bin/net: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

### Resolution
Issue 1: 
creating a symlink from /usr/lib/libreadline.so.8 to /usr/lib/libreadline.so.6 will fix it.
Issue 2:
Creating a symlink from /usr/lib/libcrypt.so.2 to /usr/lib/libcrypt.so.1 **WONT** fix this issue, instead the dependency 
[libxcrypt-compat](https://archlinux.org/packages/core/x86_64/libxcrypt-compat/) should be included to fix it.

Cheers

**Comment by D3vil0p3r** [comment] 2024-10-09 19:41
The tool has been compiled with old libs. This is the cause.

**Comment by D3vil0p3r** [comment] 2024-10-09 19:56
@noraj since this toolkit needs to be re-compiled upstream but cannot because the project is abandoned, I would add it in broken list and close the issue

https://github.com/BlackArch/blackarch/pull/4286

**Closed** 2024-10-11 20:07 UTC
Labels: type::bug
